---
output: 
  rmarkdown::html_vignette:
    toc: true
    keep_md: true
vignette: >
  %\VignetteIndexEntry{Manual for the compIntegrate pacakage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# compIntegrate package: vignette

\setcounter{tocdepth}{5}
\tableofcontents

# Introduction

# Publication

The underlying method of the compIntegrate package is described in detail in the following article: 

# Installation

The package can be installed and loaded using the following commands:

```{r load-packages, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE,
                      warning = FALSE, message = FALSE, echo = TRUE, eval = TRUE, 
                      tidy = TRUE, fig.width = 9, fig.height = 6, purl = TRUE, 
                      fig.show = "hold", cache.lazy = FALSE)
palStore = palette()
#Load all fits, to avoid refitting every time rebuilding the vignette
#load(system.file("fits", "zellerFits.RData", package = "RCM"))
```

```{r install, eval = FALSE}
library(BiocManager)
install("compIntegrate", update = FALSE)
```

```{r loadRCMpackage}
suppressPackageStartupMessages(library(compIntegrate))
cat("compIntegrate package version", 
    as.character(packageVersion("compIntegrate")), "\n")
```

# Session info

This vignette was generated with following version of R:

```{r sessionInfo}
sessionInfo()
```
